#!/bin/bash

npm install -g letsencrypt-cli@2.x

letsencrypt certonlrtonly \
  --agree-tos --email $1 \
  --webroot --webroot-path $(pwd)/public \
  --config-dir $(pwd)/ssl \
  --domains $2 \
  --server https://acme-v01.api.letsencrypt.org/directory

